### ISSUE TITLE
Compiling geofire via cocoapod in swift project

### ISSUE THREAD

**Issue by tommybananas** [firebase/geofire-objc#13]
I'm creating a new swift project, and adding these dependancies in my PodFile:
pod 'Firebase', '~> 2.2'
pod 'GeoFire', '~> 1.1'

Then I'm including them both in a bridged header:
![screen shot 2015-05-20 at 10 48 02 pm](https://cloud.githubusercontent.com/assets/2165523/7741248/513b1b12-ff42-11e4-95f4-4d25f595e657.png)

And the GeoFire.h header inside of the Pods project says it can't find the FireBase header:
![screen shot 2015-05-20 at 10 44 48 pm](https://cloud.githubusercontent.com/assets/2165523/7741228/1cf2033e-ff42-11e4-906b-592faef66e7c.png)

Any help would be appreciated, thanks!

**Comment by katfang** [comment]
This was just fixed in #14. :)

Until we push a new version to Cocoapods, you can get the updated version with:

`pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'`

If the compiler then tells you something like "Use of unresolved identifier 'GeoFire'", try importing GeoFire straight in your Swift file with `import GeoFire`.

I'll leave this open for now and post again when we've released to Cocoapods.

**Comment by tommybananas** [comment]
Thank you so much :)

**Comment by katfang** [comment]
GeoFire has now been updated to 1.1.1 on Cocoapods. Using the bridging header should work!

**Comment by a9austin** [comment]
I am having this issue again.
