### ISSUE TITLE
queryAtLocation 

### ISSUE THREAD

**Issue by Stan92** [firebase/geofire-objc#23]
Hi,
I have some doubts about the query queryAtLocation
In my example this is the query I use

gfCircleQuery = geoFire.queryAtLocation(center, withRadius:1.0)
My center point has this value
+48.85593490,+2.35885390

In meantime, I have a point (firebase) with the same location

Running the query it doesn't find the point.

But if I change the radius to 2.0 Kms.. The point is selected from my different events (.added, etc..)
Do I miss something?

**Comment by jdimond** [comment]
If you have an entry that is at the same location, then the query should return the point. Do you have the data for what's stored in Firebase (you can use the dashboard) and the exact code you are using to create the query?

**Comment by Stan92** [comment]
let geoRef = Firebase(url: appDelegate.fireBaseUrl +  "/demandes"  )
 let geoFire = GeoFire(firebaseRef: geoRef)
 let center = CLLocation(latitude:  48.85593490000003, longitude: 2.3588539)
gfCircleQuery = geoFire.queryAtLocation(center, withRadius: 1 )

handleCircleQueryEntered =  gfCircleQuery!.observeEventType(GFEventTypeKeyEntered, withBlock: { (sid: String!, position: CLLocation!) in
let itemRef = Firebase(url: self.appDelegate.fireBaseUrl +  "/demandes/"  + sid )
itemRef.observeSingleEventOfType(.Value, withBlock: { snapshot in
... 
....

Using this query there's no result.
Setting the radius to 2 I get my "demande"


![firebase](https://cloud.githubusercontent.com/assets/1044972/11861894/121309fc-a485-11e5-80a6-341a0158215c.png)

**Comment by jdimond** [comment]
GeoFire uses geohashes (you can play around with them [here](http://www.movable-type.co.uk/scripts/geohash.html)) to run the query. It seems your geohash (under the key g) and the actual location (under the key l) do not match up. That's why GeoFire cannot find the item. The location and geohash are close enough however that it shows up with the larger query.

Please only ever write/update your location with the GeoFire library, or else geohash and location might get out of sync. That should solve this issue.
