### ISSUE TITLE
GeoFireRef.setLocation method replaces all data inside the key

### ISSUE THREAD

**Issue by firecast** [firebase/geofire-objc#33]
```
geoFire.setLocation(CLLocation(latitude: 37.7853889, longitude: -122.4056973), forKey: "firebase-hq") { (error) in
  if (error != nil) {
    println("An error occured: \(error)")
  } else {
    println("Saved location successfully!")
  }
}
```

The above code replaces all data inside the key "firebase-hq" with a "g" and "l" keys with data containing the geohash and the lat long. Shouldn't this just update the values and emulate Firebase's updateChildValues rather than replace all of them.

If not, is there a way to create a geoHash and update manually using Firebase's updateChildValues method from the GeoFire framework

**Comment by jwngr** [comment]
This is expected behavior for the existing library. Setting a key overwrites the entire node.

It is not suggested you store other data inside of your GeoFire index. You should store that other data in a separate node with the same keys as your GeoFire index and look up that data whenever you need it. If that is not possible for you or you have a separate use case, please let us know what that is.

**Comment by AJMiller** [comment]
@jwngr fwiw, we just got bitten by this too, debugging why all of our data was getting wiped out on our users table, when we went back to our map view. Come to find out, as you noted, that GeoFire assumes it 'owns' the key that it's storing its location data in and will overwrite all other data stored in that key. I can take a swing at it and submit a PR, but not sure if you guys are accepting PRs at the moment.

**Comment by puf** [comment]
Keeping additional data in the geofire keys will lead to suboptimal
bandwidth usage.

Say that you're tracking busses. You have many properties for each bus such
as its number, when it was built, last service date, etc. In addition you
have the geolocation for the bus. The geolocation of bus will change
frequently, the other properties will not. By mixing these properties under
the same node, you will force your users to download the "static" data
whenever the bus moves. Not a good idea when it comes to bandwidth usage.

Geofire separate the geolocation from the other data. Now whenever the bus
comes in range of your geoquery (key_entered), you can load+sync the other
data for that bus. When the bus goes out of range (key_exited), you can
stop listening for that data. If you're worried about the number of
listeners, you can also cache the bus' data. After all it was put in a
separate node, since it is semi-static.

**Comment by AJMiller** [comment]
That makes sense for frequently moving targets. I suppose if you were
tracking restaurant locations, that would be less of an issue too so ymmv.
It turned out to not be a big deal to fix, but the comments in the header
file for GeoFire.h state that the setLocation call will “update” the
location for a key, which to me meant that it was only updating it’s own
values, not necessarily overwriting the key entirely.


On May 10, 2016 at 3:22:11 PM, Frank van Puffelen (notifications@github.com)
wrote:

Keeping additional data in the geofire keys will lead to suboptimal
bandwidth usage.

Say that you're tracking busses. You have many properties for each bus such
as its number, when it was built, last service date, etc. In addition you
have the geolocation for the bus. The geolocation of bus will change
frequently, the other properties will not. By mixing these properties under
the same node, you will force your users to download the "static" data
whenever the bus moves. Not a good idea when it comes to bandwidth usage.

Geofire separate the geolocation from the other data. Now whenever the bus
comes in range of your geoquery (key_entered), you can load+sync the other
data for that bus. When the bus goes out of range (key_exited), you can
stop listening for that data. If you're worried about the number of
listeners, you can also cache the bus' data. After all it was put in a
separate node, since it is semi-static.


On Tue, May 10, 2016 at 12:00 PM AJ Miller <notifications@github.com> wrote:

> @jwngr <https://github.com/jwngr> fwiw, we just got bitten by this too,
> debugging why all of our data was getting wiped out on our users table,
> when we went back to our map view. Come to find out, as you noted, that
> GeoFire assumes it 'owns' the key that it's storing its location data in
> and will overwrite all other data stored in that key. I can take a swing
at
> it and submit a PR, but not sure if you guys are accepting PRs at the
> moment.
>
> —
> You are receiving this because you are subscribed to this thread.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/firebase/geofire-objc/issues/33#issuecomment-218256521
>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/AA3w34ILCNFJbzHImHAx6TvuJgxuuPbvks5qANXHgaJpZM4HwxVq
>
> .
>

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/firebase/geofire-objc/issues/33#issuecomment-218262764>

**Comment by jossef** [comment]
I got here from a google search. experienced the same annoying behavior.
first of all, +1 for the question. this is a good example of bad developer-experience.

I was trying to use `addGeoQueryDataEventListener` and to parse `User` object. after I stored the user I called `geoFire.setLocation()` and yet it overridden my User object.

How should I benefit `addGeoQueryDataEventListener` if the expected behavior of `geoFire.setLocation()` is to override the object?

anyway, I looked in the source and adjusted with this small hack:

## The Hack

Add 2 data members (`g` and `l`) to my object

```
@IgnoreExtraProperties
public class User {

    public String id;
    public String name;
    public String email;
    // ....

    public String g;
    public List<Double> l;
}
```

then when I persist the `User` object, I populate `g` and `l`

```
    public static void updateUser(User user) {

        if (TextUtils.isEmpty(user.id)) {
            throw new RuntimeException("id cannot be null");
        }

        DatabaseReference databaseReference = FirebaseDatabase.getInstance().getReference();
        DatabaseReference keyRef = databaseReference.child("users");
        Map<String, Object> updates = new HashMap<>();
        updates.put(user.id, user);

        user.g = new GeoHash(user.latitude, user.longitude).getGeoHashString();
        user.l = Lists.newArrayList(user.latitude, user.longitude);

        keyRef.updateChildren(updates);
    }
```

in my `MainActivity` where I have a GoogleMaps widget, I use the following:

```

    @Override
    public void onMapReady(GoogleMap googleMap) {
        this.googleMap = googleMap;
        googleMap.setOnMarkerClickListener(this);

        googleMap.setOnCameraIdleListener(() -> {
            CameraPosition cameraPosition = this.googleMap.getCameraPosition();
            double latitude = cameraPosition.target.latitude;
            double longitude = cameraPosition.target.longitude;
            search(latitude, longitude);
        });
     }

    private void search(double latitude, double longitude) {
        GeoLocation location = new GeoLocation(latitude, longitude);
        double radius = 5;
        if (geoQuery == null) {
            geoQuery = Data.geoFire.queryAtLocation(location, radius);
            geoQuery.addGeoQueryDataEventListener(this);
        } else {
            geoQuery.setLocation(location, radius);
        }
    }

    @Override
    public void onDataEntered(DataSnapshot dataSnapshot, GeoLocation location) {

        // TODO handle current user item

        User user = dataSnapshot.getValue(User.class);

        LatLng latLng = new LatLng(location.latitude, location.longitude);

        // TODO set the id here
        MarkerOptions options = new MarkerOptions()
                .position(latLng);
        Marker marker = googleMap.addMarker(options);

        String key = user.id;
        markers.put(key, marker);
    }

    @Override
    public void onDataExited(DataSnapshot dataSnapshot) {

        User user = dataSnapshot.getValue(User.class);

        String key = user.id;

        if (markers.containsKey(key)) {
            Marker marker = markers.get(key);
            marker.remove();
            markers.remove(key);
        }

    }

```
