### ISSUE TITLE
What has happened?

### ISSUE THREAD

**Issue by Kamuli** [firebase/geofire-objc#87]
Analyzing dependencies
Pre-downloading: `GeoFire` from `https://github.com/firebase/geofire-objc.git`
[!] Unable to satisfy the following requirements:

- `Firebase/Database` required by `Podfile`
- `Firebase/Database` required by `Podfile`
- `Firebase/Database (= 3.9.0)` required by `Podfile.lock`
- `Firebase/Database (~> 4.0)` required by `GeoFire (2.0.0)`

Specs satisfying the `Firebase/Database` dependency were found, but they required a higher minimum deployment target.

Specs satisfying the `Firebase/Database` dependency were found, but they required a higher minimum deployment target.

Specs satisfying the `Firebase/Database (= 3.9.0)` dependency were found, but they required a higher minimum deployment target.

Worked fine weeks ago, but not anymore... ???

**Comment by Kamuli** [comment]
Fixed by cloning GeoFire and removed  dependency (~> 4.0)  from GeoFire.podspec:
 s.ios.dependency  'Firebase/Database'

**Comment by sagearbor** [comment]
The Geofire pod issue seems to be fixed by changing which commit of geofire-objc.git is pulled.  It is described in the github issue link below (for nativescript plugin implementation).  In short change geofire-objc.git commit dbb8d193f5ee1371837800d0502bd29cba779da4

https://github.com/shripalsoni04/nativescript-geofire-plugin/issues/3 

For nativescript only the exact fix is
> tns plugin add nativescript-geofire-plugin
> tns platform remove ios
> vi node_modules/nativescript-geofire-plugin/platforms/ios/Podfile
comment out current line and add new line below

#pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git', :commit => 'dbb8d193f5ee1371837800d0502bd29cba779da4'
pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git', :commit => '96d6463f59016785f9c5ae9b669019c44786a23f'

> tns run ios

**Comment by charlie884** [comment]
these commit doesn't work any more, out put this error

[!] CocoaPods could not find compatible versions for pod Firebase/Database:
  In snapshot (Podfile.lock):
    Firebase/Database (= 5.0.1)

  In Podfile:
    Firebase/Database

    GeoFire (from https://github.com/firebase/geofire-objc.git, commit 96d6463f59016785f9c5ae9b669019c44786a23f) was resolved to 2.0.0, which depends on
      Firebase/Database (~> 4.0)

Specs satisfying the Firebase/Database, Firebase/Database (= 5.0.1), Firebase/Database (~> 4.0) dependency were found, but they required a higher minimum deployment target.

do you have other alternative?
